# Default, Defaults
markdown: kramdown
highlighter: pygments # or rouge or null
exclude: ["node_modules", "gulpfile.js", "package.json"]

# Jekyll Defaults
title: Sanjay Shrikrishna Gokhale
email: sanjaygokhale56@gmail.com
description: Website dedicated to the cultural journey of Sanjay Shrikrishna Gokhale
baseurl: "" # the subpath of your site, e.g. /blog

# Where can people find your site?
url: "https://sanjaygokhale.github.io" #"http://127.0.0.1:4000"
# When developing, set this ^ equal to whatever localhost you're using

# Socail Media links
# Use these to link users to your organization's social media sites
# twitter:
# facebook:
# google:
youtube: https://www.youtube.com/channel/UCihhCjko-fQxS4G9sD4No4A
soundcloud: https://soundcloud.com/sanjay_gokhale

author: Chaitanya S. Gokhale
authorBio: Privileged to have a hobby as a profession, a professor in the week and a hiker on the weekends. My name is Chaitanya, and this is my father's website.
